language: ruby

before_install:
  - gem update bundler

services:
  - mongodb

rvm:
  - 2.0.0
  - 2.1.0

gemfile:
  - gemfiles/rails-3.1.gemfile
  - gemfiles/rails-3.2.gemfile
  - gemfiles/rails-4.0.gemfile
  - gemfiles/rails-4.1.gemfile
  - gemfiles/rails-4-observers.gemfile
  - gemfiles/mongo_mapper.gemfile
  - gemfiles/mongoid.gemfile
