language: ruby

services:
  - mongodb

rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0

gemfile:
  - gemfiles/rails-3.1.gemfile
  - gemfiles/rails-3.2.gemfile
  - gemfiles/rails-4.gemfile
  - gemfiles/rails-4-observers.gemfile
  - gemfiles/rails-4-protected-attributes.gemfile
  - gemfiles/mongo_mapper.gemfile
  - gemfiles/mongoid.gemfile

matrix:
  exclude:
    - rvm: 1.8.7
      gemfile: gemfiles/rails-4.gemfile
    - rvm: 1.8.7
      gemfile: gemfiles/rails-4-observers.gemfile
    - rvm: 1.8.7
      gemfile: gemfiles/rails-4-protected-attributes.gemfile
      